services:
  front:
    build: ./php
    image: anthonymasset/cp-php:latest
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

  db:
    build: ./mysql
    image: anthonymasset/cp-mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-cp-data:/var/lib/mysql

volumes:
  mysql-cp-data: